### ISSUE TITLE
Automate webWW library deployment to npm

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#152]
Closes #136

**Comment by zglueck** [comment]
## For Travis Deployment

Need to add the following to `package.json`
- [ ] Set the [module to public](https://docs.travis-ci.com/user/deployment/npm/#Troubleshooting-%E2%80%9Cnpm-ERR!-You-need-a-paid-account-to-perform-this-action.%E2%80%9D)

Need to add the following to `travis.yml`
- [ ] Authentication variables (it is unclear to me if providing an API key as an environment variable alone is enough [docs](https://docs.travis-ci.com/user/deployment/npm/#NPM-auth-token), @Beak-man did you ever use travis for publishing to npm?)

Need to add the following files
- [ ] Changelog creation script

**Comment by pdavidc** [comment]
Regarding Travis npm deployment, I've reviewed the Travis docs you linked to. My assessment is that the npm API key can be provided either as an environment variable or inline. The steps outlined under "NPM auth token" assume we want the key provided inline. Let's try the environment variable approach first, since it's much easier to maintain.

**Comment by Beak-man** [comment]
@zglueck Yes, I deployed a test package to npm's repository with Travis back when the package was non-functional due to the module definition hell. I went with the environment variables for both the e-mail and npm's token, as it can be seen here:

https://github.com/Beak-man/WebWorldWind/blob/feature/build_suggestions/.travis.yml

My Travis settings:

![screen shot 2017-09-07 at 09 41 33](https://user-images.githubusercontent.com/7622894/30169174-3d79372a-93b1-11e7-88ff-cbf45d2a2ff4.png)

**Comment by pdavidc** [comment]
Closed via #215
