### ISSUE TITLE
Enable local images in NPM package

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#164]

**Comment by Beak-man** [comment]
Web WorldWind's local images are not being loaded (e.g. compass, view controls) when the library is packaged via npm and used as a module in a Webpack-based project. One of the reasons is that the library is looking for an /images folder in the root of the web document, when as an npm package, this folder is located in /node_modules/<package_name>, which is of course where the library is located as well.

I'll try to modify Web WorldWind so it will retrieve the images with a path relative to the library instead of the document.

It has to be taken into consideration that, usually, Webpack needs local resources to be loaded with a 'require()' statement. It may be possible that there won't be a way around this if the resources are being loaded within the /node_modules folder.

**Comment by Beak-man** [comment]
The usual strategy to load local files in a CommonJS environment is to use a ´require()´ statement:

http://fredkschott.com/post/2014/06/require-and-the-module-system/

That being said, our AMD-based building tool (RequireJS) does support the statement, but I'm not sure if it works the same as in a CommonJS environment, at least when it comes to loading files.

http://requirejs.org/docs/api.html

**Comment by balhar-jakub** [comment]
Unless the CommonJS specification changed in meantime it should behave
differently as CommonJS loads the modules synchronously while requirejs
asynchronously.

As far as I remember it should be possible to load images using require and
some plugin but at least the paths and exact execution will differ.

**Comment by Beak-man** [comment]
Thanks for the insight, @balhar-jakub . As for now, we've decided to deliver the images as a separate download until we look into options of taking advantage of RequireJS features to load them from within the /node_modules folder. Then we will have to see if that doesn't mess with either the CommonJS interface somehow, or with the way we already load them from the root path of the web document.

Publishing them separately for now doesn't induce a breaking point, and for now it works as you guys mentioned in the meeting by taking advantage of a dedicated folder for such root-dependent files.

The working npm package it's working with my [simple React tester](https://github.com/Beak-man/worldwind-react), with the images bundled separately. You may see that the package itself is bundled as a .tgz file while we make the official release in npm's repository.

I'm planning to do a similar test project for Angular 2.0, which is also Webpack-based. I'll neeed to study it a bit, since it's quite different to what I studied back in the day with Angular 1.

**Comment by johnnguyen1997** [comment]
Hi all, is there a solution for this on Vue?

I read on the officical website is to place the image folder in the webroot. Is this still the case?

**Comment by Beak-man** [comment]
@johnnguyen1997 yes that's still the case, the images can be downloaded from [here](https://files.worldwind.arc.nasa.gov/artifactory/web/0.9.0/images.zip).
