### ISSUE TITLE
Research build artifact hosting and define tasks

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#183]
Research options for hosting runtime artifacts used in production applications. Define the tasks necessary to establish a service for WebWorldWind's live resources.

Key build artifacts include:
- JS library
- JS minified library
- Images
- Example apps
- Standalone data distribution (temporarily)

Hosting requirements:
- Secure HTTP connections
- Cross origin requests for all assets, including images

See http://worldwindserver.net/webworldwind for an example of our previous hosting solution.

**Comment by zglueck** [comment]
I have been researching hosting options for some of our assets, namely:
- Versioned Web WorldWind library (worldwind.min.js & worldwind.js)
- Web WorldWind Images assets (both directory and zip)
- WorldWind Java Applets
- Web WorldWind Standalone data
- Other Miscelaneous Files (presentations, etc.)

When considering options, the following criteria were considered:
- “Branding” what URL are we passing to users to retrieve the assets?
- SSL Support
- Use Limits (Storage and Bandwidth)
- Header Configuration (especially CORS and cache settings)
- Interface (API and GUI)
- Customer Support

There are a multitude of options available. I’ve primarily invested time into evaluating Bintray, MaxCDN, Unpkg, and hosting at Ames. While Bintray has a decent GUI and API for interface, our ongoing issues with support and lack of header configuration precluded it from the comparison table below.

Service | Branding | SSL Support | Use Limits | Header Configuration | Interface | Customer Support
--- | --- | --- | --- | --- | --- | ---
MaxCDN | fully customizable with paid plan | if we supply certificate | depends on plan | content mirrors source and UI provides additional cache configuration | GUI and API | email/phone response with 4? hours with paid plan
https://unpkg.com | `https://unpkg.com/<library name>` only |  yes | no* | sets cache and CORS | no interface, automatically syncs with npm | the creator on twitter
Ames | <whatever we want :)>.arc.nasa.gov/ | letsencrypt? | tbd | whatever we want | none | our team :)

Many of the CDN services (MaxCDN, Akami, and CloudFlare) provide CDN capabilities that are "put in front" of a provided webserver. This provides extra resilience and faster download times for users.

I didn't assign a quantitative measure to the evaluation criteria; however, after a discussion with Dave, I believe our branding is one of our most important customer facing components. Sending users to random urls (like unpkg) doesn't seem like a unified product approach and takes away configuration control. We also need to be able to configure headers and content in a manner which best fits our application. With these criteria, I think hosting at Ames is the best option. It requires additional team development time to configure and maintain but gives us the best control and predictability.

**Comment by pdavidc** [comment]
Given that hosting at Ames appears to be our best option, we'll need a strategy for deploying, organizing, and hosting assets at Ames.  There's an Apache HTTP server already in production:
https://github.com/NASAWorldWind/NASAWorldWind.github.io/issues/73

What approach do you think would best suit the project's needs here?

**Comment by zglueck** [comment]
What do you think of this approach?

1. Inventory all assets requiring hosting.

2. Determine the desired path/structure of the data. What should the endpoints look like? The data folder structure doesn't necessarily need to match url path, but it would significantly make things easier. If we really want continuity, it will be important to nail down a good url path strategy. That way we can always change organization/structure behind the scenes, but keep our public facing endpoints consistent. In order to limit interference with existing/future website, maybe consideration for reopening the `data` subdomain? I believe there are a number of open source content organization and hosting projects out there. I think we should avoid them for the sake of simplicity and security/maintenance overhead. Perhaps a markdown file manifest in the NASAWorldWind.github.io repository detailing the content would help picture the data structure?

3. Identify deployment mechanisms for the different data types. Some assets I imagine are pretty static in nature and will just need a one time copy. Others, particularly releases, may need some type of automated download mechanism if we decide to not manually login, and download the files.

3. Establish the machine/server/access protocol. Given the tasks we would like to accomplish, and our development teams familiarity with linux tools. I think this could be as simple as `scp`, or, an email to Randy and the listserve on content that needs to be added to our content server.

As for the actual server implementation, I vote for the solution which will be the easiest/quickest to standup in the Ames environment. If that is the Apache server you mentioned, that would work. I do think the utilization of a new subdomain would help with duplicate paths with `worldwind.arc.nasa.gov`.

**Comment by pdavidc** [comment]
This approach looks good.
- Using a subdomain would indeed avoid conflicts with the website. The data subdomain has been used for map services, so we'd need another name. Check with @RandolphKim on what's possible.
- Assets must be deployed automatically to ensure our release procedure is simple and as free of human error as possible.
- Travis CI must create the assets and deploy them somewhere. It may be possible to deploy directly to Ames if we can deploy via a service that doesn't require a VPN connection. Travis could also deploy the assets to an intermediate location where some procedure at Ames finds the assets and deploys them internally (like nasaworldwind.github.io).
- The Java WebStart assets (not applet) are under /java/version, and can be migrated to the new site.

**Comment by zglueck** [comment]
@pdavidc with how the hosting endpoints of the libraries are spread out right now (GitHub, Bintray, npm) I think a robust and simple npm project on the content server could monitor the API's for project updates and download the requisite files as needed to the content directory. This would be an Ames "pull" methodology, which I think is easier (from both an implementation and environment viewpoint) to implement than a "push" method from Travis.

**Comment by zglueck** [comment]
This issue is closing with the creation of the tasks associated with #199.
