### ISSUE TITLE
Adjust CustomPlacemark example to avoid terrain clipping

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#315]
Very minor. 

### Description

When tilting the globe with altitude 1000km the placemark partially sunk to the terrain.

### Operating System and Version

Windows 10 / Edge 40

**Comment by pdavidc** [comment]
Placemark is designed to be obscured by terrain; I've re-titled this issue to reflect that distinction. That said, I can see how this would look like a bug, so perhaps we ought to change the CustomPlacemark example to match the user's expectation. Here are two ways we could adjust the example:

• Align the placemark image on the bottom-center, rather than the true center. Other placemark examples do this, though it's not obvious.
• Disable depth testing in the example's PlacemarkAttributes.

@AkeluX @markpet49 What are your thoughts?

**Comment by AkeluX** [comment]
This example actually shows the intended behaviour for this situation. Consequently, I'm not sure anything should be done with respect to this issue.

Nonetheless, I see the point of matching the user's expectation. In my opinion, it is to be balanced with the role of the examples to simply show what the framework offers.

If we do something, I would go for the first proposition because it is simple and doesn't act on a more complex concept like depth testing. I believe an app developer will understand more easily what positioning the image means than why is depth testing disabled in this case.

**Comment by pdavidc** [comment]
Sound reasoning @AkeluX. Let's keep the example as is.
