### ISSUE TITLE
Firefox: Upper part of rendered text is cut off

### ISSUE THREAD

**Issue by strikerM** [NASAWorldWind/WebWorldWind#344]
### Description

Upper part of text is slightly cutoff.
The issue seems to affect any text rendered with WebWorldWind.

### Steps to Reproduce

1. Open the ScreenText example.

**Reproduces how often:** 100%

### Operating System and Version

macOS High Sierra 10.13.1 / Firefox 57.0 (64-bit)

### Additional Information

![ss_text](https://user-images.githubusercontent.com/14248863/32944168-3eaf5552-cb97-11e7-8658-60f624192da5.png)

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by zglueck** [comment]
The core of this issue relates to [CanvasRenderingContext2D.textBaseline](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline).

In TextRenderer we specify the textBaseline to be `top`. Chrome and Firefox do not draw text consistently between the different options. Examine the example provided by the Mozilla documentation linked above in Chrome vs Firefox:
![screen shot 2018-02-20 at 1 33 55 pm](https://user-images.githubusercontent.com/4935133/36445077-c4793b94-1642-11e8-986f-7d0f758e2903.png)

There seems to be some disagreement over how to draw the different options.

This issue was noted 6 years ago in Firefox's own bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=737852

And is also being tracked in the HTML spec:
https://github.com/whatwg/html/issues/2470
