### ISSUE TITLE
Improve the reusability and extensibility of ShapeEditorController

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#427]
Child of #511 

### Description

When working on one of our projects we discovered that we need ShapeEditorController, which controls the editing for just one shape instead of for all shapes. 

With current design it means that the whole ShapeEditorController needs to be copied and updated as the relevant methods are internal methods in the constructor and therefore it isn't possible to replace them in the descendant.

Proposal:
Update the constructor of the ShapeEditorController by moving these methods as protected methods on the object itself. This way it simplifies creation of descendants of the class.

**Comment by AkeluX** [comment]
@balhar-jakub I also have my doubts about the API proposed in the shape editor branch. However, I believe your proposed solution would only be a quick technical workaround and the tool instead needs more thoughts overall. The goal was to have something similar to WorldWindJava, but limited to surface shape. You'll see this in my email about tasks in January.
I understand that your scenario is to choose the shape to edit at the app level and not have an implementation that makes all shapes editable without further control. Let me know otherwise. We'll take this into consideration.

**Comment by AkeluX** [comment]
The version in #637 addresses these points.
