### ISSUE TITLE
SurfaceShape does not render changes of the attributes

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [NASAWorldWind/WebWorldWind#47]
After updating an attribute (such as the interior color) of a SurfaceShapeTile renderable,  the method to check if anything changed: "SurfaceShapeTile.prototype.needsUpdate", returns false, while it should return true.
Thus, the shape does not change on the globe.

**Comment by AkeluX** [comment]
I've tried to reproduce this one in the SurfaceShapes example with only the first SurfacePolygon and the code below.

```javascript
document.getElementById("trigger").addEventListener("click", function() {
    shape.attributes.interiorColor = new WorldWind.Color(1, 0, 0, 0.5);
    wwd.redraw();
});
```

I've also tried a few other attributes and they all seem to work fine. @GabrielePrestifilippo could you provide a piece of code reproducing this issue? Thank you.

**Comment by GabrielePrestifilippo** [comment]
I've tried using your code, but the opacity seems not working. 
Could you try having a look here and let me know?
http://jsbin.com/bobajugaxa/1/edit?html,js,output

**Comment by AkeluX** [comment]
I’ve figured this one out. The ShapeAttributes use its setters to invalid the state key. This works fine when a new outline or interior color is set by completely replacing the Color object. It doesn’t when a property (red, blue, green or alpha) of the previously set color is changed directly because the setter in ShapeAttributes isn’t called in this case.

I see three solutions:

1. In the getter of stateKey in ShapeAttributes, we check for the properties in Color in order to invalid the key if they change. This would mean a lot of checks with likely an impact on performance. 
2. We add a stateKey in Color that ShapeAttributes can check. This would limit the number of comparisons and work similarly to a Shape checking for changes in ShapeAttributes.
3. We leave it as is because this will all disappear with the new way of drawing surface shapes we are working on. In the meantime, we recommend to people to replace the full Color object as workaround.

What do you think?

**Comment by AkeluX** [comment]
We've discussed this in the team and decided to go with the proposition 3. We believe that the changes required in the other propositions aren't worth implementing at this point with the coming changes in surface shapes and the simplicity of the proposed workaround in the meantime.
