### ISSUE TITLE
KML Example inconsistent behaviour

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#481]
Child of #565

### Description
The KML Example demonstrates the following inconsistent behaviours:
1. Initially, without the Sentinel-2 Imagery checkbox checked, a Sentinel image shows up in the vicinity of Germany. This image disappears and reappears farther south as you zoom in (See attached screen shots)
2. Unchecking KML Samples initially turns off the polygons in the vicinity of Poland, toggling the Polygon checkbox off and then on causes them to persist when unchecking KML Samples. 

### Steps to Reproduce

1. Run KMLExample
2. Rotate the globe so that europe is visible.

### Operating System and Version

Ubuntu 16.04/Chrome 64

![ss1](https://user-images.githubusercontent.com/5826820/36613836-4f8adce2-18a0-11e8-8fb8-78e00de34395.png)
![ss2](https://user-images.githubusercontent.com/5826820/36613842-53cc646a-18a0-11e8-9cb8-a94836739b6e.png)

**Comment by balhar-jakub** [comment]
This Behavior is a complex one and some pieces of it aren't bugs but instead intentional usage of the KML Features. 

1) The image near the borders of the Germany shows and hides because it is connected to the Region element which says it should be vissible only in certain distance. 
Image showing to the south is actually different image with different settings of the Region element. 
2) It is intended that the lower level checkbox change persists even when the top level changes but only when user interaction changed it. I am not even sure what would be the perfect model as there are actually 6 different properties coming in the play when you decide whether the element should be displayed. 

This is more of an explanation of what is happening behind the scenes. The Number 2 is probably something I don't want to change or at least I am a bit unsure about how it should happen. 

As for Number 1) I propose that I will change the imagery that is shown in the two cases. First being the satellite imagery and second some other type of image so that is less confusing. I would like to hear thoughts on this.

**Comment by AkeluX** [comment]
@markpet49 any thoughts on the feedback from @balhar-jakub?
