### ISSUE TITLE
Evaluate screen credits as DOM elements

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#577]
Closes #489

Evaluate the possibility of displaying screen credits as DOM elements. This is an investigatory task. We're looking for data points that can inform our decisions, not production code.

Requirements for this task: 
- Work within the existing ScreenCreditController interface.
- Operate on the browser's DOM using JavaScript. Do not rely on any HTML or CSS files in the SDK or in the application.

Output from this task:
- Functional validation: are all browsers able to overlay attribution DOM elements on WebGL without issue?
- Performance measurement: what time does it take to refresh an attribution DOM element, and where is that time spent? 
- Impact on compatibility: are applications able to capture a screen shot that includes the attribution DOM elements?
- Impact on interfaces: does the existing ScreenCreditController interface present any obstacles to using DOM elements?

**Comment by pdavidc** [comment]
@Beak-man @markpet49 I've outlined rough requirements and expected output for this task. Please let me know if you notice anything that's missing.

**Comment by pdavidc** [comment]
Mentioning @AkeluX in case he has any insight or questions as this task develops.

**Comment by Beak-man** [comment]
These are the findings that came out of this investigation.

The DOM permits JavaScript to programatically access and manipulate every HTML element, attribute, and CSS style in any given page. We can add DOM-based screen credits without relying on additional HTML or CSS files.

In [this functional example](https://github.com/NASAWorldWind/WebWorldWind/blob/example/DOM_screen_credits/examples/DOMScreenCredits.js) we can see that HTML-based screen credits are added, both their elements and styling, via JavaScript alone (lines 48-75). Most importantly, we can access the DOM tree programatically, without making assumptions on what any given application DOM looks like. In line 82 we see the way to programatically access the the `WorldWindow` canvas parent node in order to append the newly generated HTML element. Note that this would work even if we have no idea of what the whole web application looks like above the canvas node in the DOM tree, since every canvas element has to be a child of another element:

```javascript
wwd.canvas.parentNode.appendChild(creditsOverlay);
```
[In here](https://www.w3schools.com/js/js_htmldom_document.asp) we can see all the functions that permit us to access the DOM via the document object.

There are many ways to overlay HTML elements over another. What's important to take into account is that alignment that's induced via the CSS `position` property, is done according to the parent node of the element to which the property is assigned to.

Overlaying an HTML element over another is usually done by making the intended overlay a child element of the parent node, then setting the parent's position as `relative` and the child's as `absolute` ([e.g. here](https://stackoverflow.com/questions/2941189/how-to-overlay-one-div-over-another-div)), but this doesn't work when the parent node is a canvas. No `innerHTML` or child node of a canvas is rendered by the browser, unless the browser doesn't support WebGL. Any attempt of making a child node of a canvas to render was fruitless.

It was found that two arrangements are the most conducive of what we want to do here.

- Generating and appending the overlay element as a sibling of the canvas node


Since in this case the overlay will be initially aligned according to the canvas' parent node (**not** the canvas itself), computing the offset between the element that contains both the canvas and the overlay is required. This is exemplified in lines 77 to 80 in the example:

**Comment by Beak-man** [comment]
**Option 2. Generating a new parent node that we control and exchange it for the canvas in the DOM tree**

This option can be separated in 3 different steps. 

1) Generate the overlay node where credits will be drawn and a container that will overlap the canvas and fit its layout constraints.

![2018-04-09 5](https://user-images.githubusercontent.com/7622894/38521664-f1a93dfa-3c0b-11e8-8be6-1454813abda3.png)

2) Exchange the canvas node for the new overlay in the DOM tree. Thus we have control over the parent node that contains both the canvas and the overlay, so it can have exactly the properties and layout that we need (e.g: a `block` element that with `relative` position, with sizing identical to the canvas).

![2018-04-09 7](https://user-images.githubusercontent.com/7622894/38521967-ca6c740e-3c0c-11e8-85d5-44687e8690fd.png)

3) Attach the properly configured and generated overlay node. Since we now have full control over the container parent node, and since the latter fits the canvas exactly, we don't need to account for offsets between the canvas and the application defined former parent node.

![2018-04-09 9](https://user-images.githubusercontent.com/7622894/38522079-1f29ceec-3c0d-11e8-8018-f5ebd49498b1.png)

**Advantages**
We now have full control over the canvas container and can set properties accordingly in order to avoid offset computing in a layout that it's part of the application domain, not WorldWind as a library. It can also serve as a way to add more HTML overlays in the future (see next comment).

**Disadvantages**
We´re modifying the usual location in the DOM tree for the WorldWindow canvas. Some WebUI developers may be relying on its location, so this hypothetical switch would need to be properly documented. This switching of nodes may be considered a disruption that redefines the domain of WorldWind, which usually begins below (or at the very least, at the same level) of a canvas in a DOM tree. We're extending this domain to another element (say, a div) above the canvas with this method.

**Comment by Beak-man** [comment]
**Compatibility**
Both options mentioned above were tested in Chrome, Firefox, Edge, and even Internet Explorer without issues. Screenshots work in all the desktop versions of these browsers, plus the mobile versions of Firefox and Chrome were successfully tested as well. Testing it in Safari is still pending, however.

No performance drop was perceived whatsoever, not even when the HTML had semi-transparency, via CSS opacity setting.

**Comment by AkeluX** [comment]
Unless the positioning is absolute or we find a nice way to let the browser handle it, option 1 would indeed need to consider many situations. If the DIV is positioned in an absolute manner, then the window changing size or the canvas (programmatically for example) would have to be considered.

I'm afraid that option 2 as it is presented could cause issues with layouts, styling and possibly with modern frameworks that basically manages the DOM for the app developer. Is this something that could be evaluated, e.g. how Angular and React would handle this? I don't know exactly how they decorate raw elements in jQuery, but they might use a similar approach. Could it be something to look at? If we go for option 2, we might as well do it when WebWW is initialised independently of the screen credits. This would create consistency and will be useful for future evolutions, e.g. for ballons with HTML content.

Hypothetical option 3: We could simply document that for using screen credits (and other features) the canvas has to be in a DIV with position relative created by the app developer, and then rely on this fact for the placement of the two sibling elements. We could check this when initialising a screen credit and write a warning in the console if this isn't the case.

**Comment by Beak-man** [comment]
@AkeluX , I had the feeling that option 2 would give headaches to WebUI developers, and you just pointed out why. You are most assuredly right when it comes to modern frameworks. I've got no idea if they continuously traverse the DOM tree to account for any potential node replacement or deletion done externally from the framework. Since the Angular and React devs put a lot of effort on performance, this doesn't seem likely.

Your option 3 seems to be the better way to add such a feature while maintaining basic backwards compatibility. This without breaking anything in the application's DOM. Thanks for the insight. I would go with that if we decide to support HTML overlays.

As for now, this investigation is done. This will be useful if we decide to pursue DOM overlays in WebWW in the future.
