### ISSUE TITLE
Remove image attribution support

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#644]
Child of #489

Using string attributes avoids issues with image credits with unpredictable sizing and content when the images are provided by web services.

- Refactor the existing image credit for the Bing image layer as a layer-specific screen image (#659).
- Remove support for image credits.

**Comment by Beak-man** [comment]
After a review of Bing's [API Brand Guidelines](https://www.microsoft.com/en-us/maps/mobile-brand-guidelines), and how other mapping APIs handle Bing's tiles attributions, it seems that we require to use the logo (and by extension, an image credit) at the very least for this provider.

In the link above, they provide some .pngs to use as logo, and they also state that it can be retrieved from their REST service, which can be [seen here](http://dev.virtualearth.net/Branding/logo_powered_by.png). Curiously the .pngs and the REST logos are different, the latter being the same we currently use, albeit in lower resolution.

I saw a case with Leaflet where they provide attributions via text only, but this is not part of the Leaflet library. Leaflet supports Bing Maps through a 3rd party extension ([link](https://github.com/digidem/leaflet-bing-layer)).

I think we will need to keep image credits, and not only due to Bing. Other commercial providers could hold similar guidelines that require displaying a logo.

**Comment by pdavidc** [comment]
Given the Bing attribution requirements, we've decided to keep the Bing layer's credit as an image, but refactor that functionality as a Bing layer specific screen image. Once that's complete, we'll remove support for image credits. Bing is the only layer requiring an image attribution.
