### ISSUE TITLE
Refactor Bing attribution as a screen image

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#659]
Child of #489

The Bing layer's image attribution is a special case, and its requirements are unlike attributions coming from public services. Our relationship with the Bing team requires that the Bing logo must always be visible when the Bing layer is displayed, and there is no official text alternative to the Bing logo.

1. Replace the Bing layer's usage of image credits with a layer-owned screen image. Place it somewhere it does not conflict with existing screen shapes.

2. Automate retrieval of the Bing attribution URL from the web service, and remove the built-in Bing image.

3. Provide control over the Bing attribution screen location.

**Comment by Beak-man** [comment]
The possibility of implementing the 2nd bullet point of this issue was investigated.

The `BrandLogoUri` field in the retrieved imagery metadata from Bing's REST services restricts CORS. This is the case with the URL http://dev.virtualearth.net/Branding/logo_powered_by.png, either with the secure or insecure http version. As per [Bing's docs ("Examples" section)](https://msdn.microsoft.com/en-us/library/ff701716.aspx), there doesn't seem to be another source from the web service.

This is not the case with the tiles themselves, that permit CORS and are able to be consumed by a ScreenImage. It seems that the consumption of this logo was never intended for web applications, so I recommend we keep our current locally hosted file.

Both the web service logo and the file that we have in our repository are of the exact same file size, resolution, and file type.

**Comment by Beak-man** [comment]
As for now, we've decided to keep using our locally hosted logo due to the reasons mentioned above.
