### ISSUE TITLE
KML`s tag Pair   ,getStyle is wrong

### ISSUE THREAD

**Issue by QingMings** [NASAWorldWind/WebWorldWind#77]
[Pair](https://github.com/NASAWorldWind/WebWorldWind/blob/master/src/formats/kml/util/Pair.js)
the line 94 
    `   StyleResolver `  Should not be used directly，
Here is KML for testing
 [huoche.kml](https://github.com/QingMings/kmlupload/blob/master/huoche.kml)

**Comment by balhar-jakub** [comment]
If I understand it correctly, the highlight style isn't applied correctly? Is there anything else?
I will take a look at possible fix.

**Comment by QingMings** [comment]
yes , the Pair tag  not correct analysis, hope  you fix it ,thanks :)

**Comment by QingMings** [comment]
@balhar-jakub  
How to know a KML file rendering complete,
in my code : 
`kmls.getKmlData().then(function(kmlFile){`    
                 ```          var renderableLayer = new WorldWind.RenderableLayer('kmlLayer')```
                  `         renderableLayer.addRenderable(kmlFile);`
                  `          kmls.wwd.addLayer(renderableLayer);`
                 `          kmls.wwd.redraw();`
`})`

when `wwd.redraw()`,  `kmlFile` is  not rendering complete,so the screen is blank ,Until I drag the mouse, trigger `redraw`

**Comment by balhar-jakub** [comment]
It seems to me that what you want to get is the moment when you can call redraw on the globe so that the KML is displayed. 

The KmlFile constructor returns Promise. When this promise is resolved, the KmlFile is ready for the rendering. If at this moment you call redraw on the WorldWindow it should correctly display the KML file. There is an example in the KmlExample.js in the examples section. This is a simplified version which simply adds the KML File. 

    var kmlFilePromise = new KmlFile('data/KML_Samples.kml', []);
    kmlFilePromise.then(function (kmlFile) {
            var renderableLayer = new WorldWind.RenderableLayer("KML file shapes");
            renderableLayer.addRenderable(kmlFile);

            wwd.addLayer(renderableLayer);
            wwd.redraw();
        });

I am not sure what getKmlData() call does. Could you please provide this piece of the code? Maybe there is something going on in there, that I am missing.

**Comment by QingMings** [comment]
![image](https://cloud.githubusercontent.com/assets/22107668/24100250/5c229736-0dae-11e7-9041-1dbdcc88c576.png)


just  pass parameter  ,return `new KmlFile`。
thanks .

**Comment by AkeluX** [comment]
@QingMings we've merged the fix for the original issue described in this thread. Could you confirm that this is solved for you? Thank you.

**Comment by QingMings** [comment]
Yes.  It  work fine.

**Comment by AkeluX** [comment]
Thanks.
