### ISSUE TITLE
Request for outlineColor property for TextAttributes

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#97]
It would be convenient to have a text outline color to provide contrast to GeographicText shapes.

**Comment by pdavidc** [comment]
Jay, WebWorldWind text labels have a black outline. It sounds like the problem is that this default black outline doesn't work well with the text labels produced by the Mission Command MIL-STD-2525 renderer https://github.com/missioncommand/mil-sym-js. Is that correct? If so, would you be willing to provide a screen shot demonstrating the problem?

**Comment by jaybarra** [comment]
![poor_contrast_text](https://cloud.githubusercontent.com/assets/25465248/24118638/e3125e54-0d84-11e7-9baa-13170a92e1a8.PNG)

![better_contrast](https://cloud.githubusercontent.com/assets/25465248/24118745/44a050ae-0d85-11e7-80c6-60737f6b6102.PNG)

The main text color can be altered by the user and that does work, however in other engines there is the capability of altering the text outline color.

**Comment by pdavidc** [comment]
NASAWorldWind/NASAWorldWind.github.io#79 captures the general need and epic for both WorldWind Android and Web WorldWind.

**Comment by pdavidc** [comment]
Text outline color support is in the develop branch. See epic #173 and its sub-tasks for details.
